### ISSUE TITLE
训练图片链接失效

### ISSUE THREAD

**Issue by mukuyoubi** [ystyle/tensorflow-yys#1]
训练图片链接失效了，这写图片我从阴阳师里截屏出来是否也可以？

**Comment by ystyle** [comment]
可以啊， 但图片分类比较多， 不过可以优化下。好久没玩了， 不知道界面有没有变化
链接：https://pan.baidu.com/s/1UZp4nUBupCLziTJlkLdzjg 密码：uega

**Comment by mukuyoubi** [comment]
感谢！
