### ISSUE TITLE
请问下本项目还有在维护吗

### ISSUE THREAD

**Issue by yk133** [ystyle/tensorflow-yys#3]
除了需要重新截图外还有什么坑需要踩？

**Comment by ystyle** [comment]
呃，我就用了一两个月， 后面弃坑了就没管过了。。。

重新截图，看看tf的版本对应的方法有没有修改， 还有界面修改了的话，各个 操作要自己重新配置点击的位置 

这玩意只是是界面分类器，点击部分还是手动配置 坐标位置的

**Comment by yk133** [comment]
好的，谢谢
